GET  http://localhost:4000/app/verify
Content-Type: application/json

{
    "Enrollment":"18103199",
    "Room":"1951",
    "Contact":"9805872999",
    //"ID":{"Data":"/xyz",
    //"ContentType":"image/jpg"
}